apiVersion: v1
appVersion: "v2.2.0"
description: Quobyte CSI Helm chart
name: quobyte-csi-driver
version: "2.2.0"
kubeVersion: "1.22-0 - 1.35-0"
icon: https://quobyte.github.io/quobyte-k8s-resources/images/quobyte.png 
keywords:
- Quobyte
- storage
- csi
- provisioning
sources: 
- https://github.com/quobyte/quobyte-csi
home: https://www.quobyte.com
