apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
type: "kubernetes.io/quobyte"
data:
    # "Tenant Admin" access key, base64 encoded
    accessKeyId: <yourEncodedKeyID> 
    accessKeySecret: <yourEncodedKeySecret>

