apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: "kubernetes.io/quobyte"
data:
    # "Tenant Member" access keys, base64 encoded
    accessKeyId: <yourEncodedKeyID> 
    accessKeySecret: <yourEncodedKeySecret>

