kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: accesskey-claim
  annotations: {
    user-secret: user-secret, 
  }
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: quobyte-byos 
