apiVersion: v1
kind: Secret
metadata:
  name: my-tenant-admin-secret 
  namespace: kube-system
type: "kubernetes.io/quobyte"
data:
    # "Tenant Admin" access key, base64 encoded
    accessKeyId: <yourEncodedKeyID> 
    accessKeySecret: <yourEncodedKeySecret>

