apiVersion: v1
kind: Secret
metadata:
  name: member-a-secret
type: "kubernetes.io/quobyte"
data:
    # "Tenant Member" access keys, base64 encoded
    accessKeyId: <yourEncodedKeyID> 
    accessKeySecret: <yourEncodedKeySecret>
